# ----
# Site

title: Clare's Cookbook
description: A collection of Clare Liguori's personal recipes
url: https://www.clareliguori.com/recipes/
baseurl: '/'
sourceurl: https://github.com/clareliguori/recipes
logo: /images/jam.svg

author:
  name: Clare Liguori
social:
  name: Clare Liguori's recipes
  links:
    - https://github.com/clareliguori/recipes

google_analytics_key:

# -----
# Build

timezone: America/Los_Angeles

paginate: 10
paginate_path: "/:num/"
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      push_sidebar_down: true
      print_stylesheet: true
      comments: true
      _options:
        content:
          width: 1560
          height: 2000
        featured_image:
          width: 1560
          height: 2000
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
      push_sidebar_down: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - vendor

_options:
  author_image:
    width: 400
    height: 400
