on:
  [pull_request, push]

name: Check

jobs:
  check:
    name: Build Jekyll site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - run: |
        bundle exec jekyll build
